#!/bin/bash

#
# Create master branch to track synced/master (if necessary)
# and keep the working directory updated to master after every push
#

# change into working directory
cd ..
unset GIT_DIR

# check if there is a master branch,
#  if not create it and let it track synced/master
if ! git show-ref --verify --quiet refs/heads/master ; then
	echo "Create master branch to track synced/master"
	git checkout -t synced/master
fi

# checkout and merge in synced/master
echo "Update master branch"
git checkout master -q
git merge synced/master
